# Generated by Django 4.2.29 on 2026-08-24 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='FCM registration token', max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'اندروید'), ('IOS', 'iOS'), ('WEB', 'وب')], default='ANDROID', max_length=10)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False once FCM reported the token as unregistered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this device', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توکن دستگاه',
                'verbose_name_plural': 'توکن\u200cهای دستگاه',
                'ordering': ['-updated_at'],
            },
        ),
    ]
