# Generated by Django 4.2.29 on 2026-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
