# Generated by Django 4.2.29 on 2026-07-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_addonpack_appointment_pack'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='addonpurchase',
            new_name='accounting__track_i_b61440_idx',
            old_name='accounting__track_i_addon_idx',
        ),
        migrations.RenameIndex(
            model_name='addonpurchase',
            new_name='accounting__status_3ca978_idx',
            old_name='accounting__status_addon_idx',
        ),
        migrations.RenameIndex(
            model_name='addonpurchase',
            new_name='accounting__user_id_ad6a56_idx',
            old_name='accounting__user_st_addon_idx',
        ),
    ]
