# Generated by Django 4.2.29 on 2026-08-09 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_rename_accounting__track_i_addon_idx_accounting__track_i_b61440_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('sms_monthly', 'پیامک — سهمیه ماهانه'), ('sms_wallet', 'پیامک — کیف\u200cپول'), ('appointment_monthly', 'نوبت — سهمیه ماهانه'), ('appointment_wallet', 'نوبت — کیف\u200cپول')], max_length=20)),
                ('delta', models.IntegerField(help_text='تغییر (می\u200cتواند منفی باشد) — به کنوانسیون در docstring مدل توجه کنید')),
                ('balance_after', models.IntegerField(help_text='مقدار دقیقی که باید بلافاصله پس از این رویداد در Redis باشد')),
                ('reason', models.CharField(help_text='کد ماشین\u200cخوان، مثل booking / sms_send / addon_purchase', max_length=50)),
                ('ref_type', models.CharField(blank=True, default='', max_length=50)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'metric', 'created_at'], name='accounting__user_id_bd90c9_idx'), models.Index(fields=['user', 'created_at'], name='accounting__user_id_cbb696_idx')],
            },
        ),
    ]
