# Generated by Django 4.2.29 on 2026-07-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='business.business')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='visitor.visitor')),
            ],
            options={
                'db_table': 'sms_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
