# Generated by Django 5.2.16 on 2026-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_remove_visitor_unique_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
