# Generated by Django 5.2.16 on 2026-07-30 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_user'),
        ('business', '0009_business_is_locked'),
        ('visitor', '0004_smslog_error_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPOINTMENT_BOOKED', 'نوبت گرفته شد'), ('APPOINTMENT_STATUS_CHANGED', 'وضعیت نوبت تغییر کرد'), ('APPOINTMENT_CANCELLED', 'نوبت لغو شد'), ('PROFILE_UPDATED', 'اطلاعات مراجع ویرایش شد'), ('ARCHIVED_BY_OWNER', 'از لیست کسب\u200cوکار بایگانی شد'), ('RESTORED_BY_OWNER', 'به لیست کسب\u200cوکار بازگردانده شد')], max_length=32)),
                ('actor_type', models.CharField(choices=[('VISITOR', 'مراجع'), ('OWNER', 'کسب\u200cوکار'), ('SYSTEM', 'سیستم')], max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_activities', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_activities', to='appointment.appointment')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_activities', to='business.business')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='visitor.visitor')),
            ],
            options={
                'db_table': 'visitor_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visitor', '-created_at'], name='visitor_activity_recent_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_visitors', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='visitor.visitor')),
            ],
            options={
                'db_table': 'visitor_archive',
                'ordering': ['-archived_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'visitor'), name='unique_owner_visitor_archive')],
            },
        ),
    ]
