# Generated by Django 5.2.16 on 2026-07-31 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_visitoractivity_visitorarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='visitor.visitor'),
        ),
    ]
