# Generated by Django 5.2.16 on 2026-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_smslog_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED_QUOTA', 'Skipped (quota exhausted)')], default='SENT', max_length=20),
        ),
    ]
