# Generated by Django 4.2.29 on 2026-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_smslog_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='marketing_opt_out',
            field=models.BooleanField(db_index=True, default=False, help_text='اگر فعال باشد، این مراجع در فهرست\u200cهای بازاریابی پلتفرم (خارج از پیامک\u200cهای خودِ کسب\u200cوکار) قرار نمی\u200cگیرد.'),
        ),
    ]
