# Generated by Django 4.2.29 on 2026-08-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_alter_smslog_status'),
        ('visitor', '0007_visitor_marketing_opt_out'),
    ]

    operations = [
    ]
