# Generated by Django 4.2.29 on 2026-08-29 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_restore_wrongly_hidden_businesses'),
        ('appointment', '0012_appointment_reminder_visitor_push_sent_at'),
        ('visitor', '0008_merge_20260810_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('WEB', 'وب')], default='WEB', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='visitor.visitor')),
            ],
            options={
                'db_table': 'visitor_device_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=20)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_logs', to='appointment.appointment')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='business.business')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='visitor.visitor')),
            ],
            options={
                'db_table': 'push_log',
                'ordering': ['-sent_at'],
            },
        ),
    ]
