# Generated by Django 4.2.29 on 2026-07-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Lock expiry time (locked_at + 15 min). Slot is freed after this.', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this slot was locked by a client', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Receipt / transaction number submitted by the client for card-to-card payment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='Auto-generated code shown to client as their booking reference', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'قفل شده (در حال پرداخت)'), ('PENDING_VERIFICATION', 'در انتظار تأیید فیش'), ('PENDING_APPROVAL', 'در انتظار تأیید مالک'), ('CONFIRMED', 'تأیید شده'), ('WAITING', 'در صف انتظار'), ('IN_PROGRESS', 'در حال سرویس'), ('COMPLETED', 'تکمیل شده'), ('NO_SHOW', 'غیبت'), ('CANCELLED', 'لغو شده')], db_index=True, default='WAITING', max_length=25),
        ),
    ]
