# Generated by Django 4.2.29 on 2026-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_add_payment_sms_lock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Uploaded receipt image for card-to-card payment', null=True, upload_to='payment_receipts/'),
        ),
    ]
