# Generated by Django 4.2.29 on 2026-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_payment_method',
            field=models.CharField(choices=[('NONE', 'بدون بیعانه'), ('CARD', 'کارت به کارت'), ('GATEWAY', 'درگاه پرداخت آنلاین')], default='NONE', help_text='How the deposit (if any) was paid — so an owner seeing the client in person for the remainder knows a deposit was already collected, and through which channel.', max_length=10),
        ),
    ]
