# Generated by Django 4.2.29 on 2026-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_deposit_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='selected_services',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
