# Generated by Django 4.2.29 on 2026-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_appointment_selected_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_push_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When the owner's push reminder was sent (null = not yet). Separate from reminder_sent_at because the two travel on different channels to different people: the client's SMS only goes out for PANEL businesses and costs quota, while the owner's push is free and goes out for every business with notifications on. One shared stamp would make a sent SMS suppress the push, and vice versa.", null=True),
        ),
    ]
