# Generated by Django 4.2.29 on 2026-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_appointment_reminder_push_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_visitor_push_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When the client's push reminder was sent (null = not yet). A third, independent stamp alongside reminder_sent_at (client SMS) and reminder_push_sent_at (owner's push) — same reasoning: one shared stamp would make one channel silently suppress another.", null=True),
        ),
    ]
