# Generated by Django 4.2.29 on 2026-03-21 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=20)),
                ('version_code', models.IntegerField(unique=True)),
                ('force_update', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
        migrations.CreateModel(
            name='VersionChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=list)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='versions.appversion')),
            ],
        ),
    ]
