# Generated by Django 4.2.29 on 2026-08-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_restore_wrongly_hidden_businesses'),
        ('bale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('to_status', models.CharField(max_length=20)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='business.business')),
            ],
            options={
                'db_table': 'bale_pending_reason',
                'ordering': ['-created_at'],
            },
        ),
    ]
