# Generated by Django 4.2.29 on 2026-05-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, help_text='Business logo image', null=True, upload_to='business_logos/')),
                ('default_service_duration', models.IntegerField(help_text='Default duration in minutes')),
                ('work_start_hour', models.IntegerField(help_text='0-23')),
                ('work_end_hour', models.IntegerField(help_text='0-23')),
                ('notification_enabled', models.BooleanField(default=True)),
                ('notification_types', models.CharField(default='SMS', help_text='Comma-separated: SMS,WHATSAPP,TELEGRAM', max_length=100)),
                ('notification_minutes_before', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this business', on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='business_user_id_720264_idx')],
            },
        ),
    ]
