# Generated by Django 4.2.29 on 2026-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_anonymous_view',
            field=models.BooleanField(default=False, help_text='If True, guests can view contact details (phone, address, etc.)'),
        ),
    ]
