# Generated by Django 4.2.29 on 2026-07-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_allow_anonymous_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='allow_anonymous_view',
            field=models.BooleanField(default=True, help_text='If True, guests can view contact details (phone, address, etc.)'),
        ),
    ]
