# Generated by Django 4.2.29 on 2026-07-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_allow_anonymous_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='card_number',
            field=models.CharField(blank=True, default='', help_text="Owner's card number shown to clients — required when payment_method=CARD", max_length=19),
        ),
        migrations.AddField(
            model_name='business',
            name='card_owner_name',
            field=models.CharField(blank=True, default='', help_text='Name on the card, displayed alongside card_number', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='enable_promotional_sms',
            field=models.BooleanField(default=False, help_text='Allow sending promotional/marketing SMS to clients'),
        ),
        migrations.AddField(
            model_name='business',
            name='enable_reminder_sms',
            field=models.BooleanField(default=True, help_text='Send appointment reminder SMS to clients'),
        ),
        migrations.AddField(
            model_name='business',
            name='merchant_id',
            field=models.CharField(blank=True, default='', help_text='Zibal merchant ID — required when payment_method=GATEWAY', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='payment_method',
            field=models.CharField(choices=[('NONE', 'رایگان / بدون پیش\u200cپرداخت'), ('CARD', 'کارت به کارت'), ('GATEWAY', 'درگاه آنلاین (زیبال)')], default='NONE', help_text='How clients are charged when booking', max_length=10),
        ),
    ]
