# Generated by Django 4.2.29 on 2026-07-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_add_payment_sms_lock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='booking_enabled',
            field=models.BooleanField(default=True, help_text='If False, clients cannot create new appointments'),
        ),
        migrations.AddField(
            model_name='business',
            name='notice_message',
            field=models.TextField(blank=True, default='', help_text='A short notice shown to clients on the booking page (e.g. vacation, holiday)'),
        ),
    ]
