# Generated by Django 4.2.29 on 2026-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_add_notice_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text="List of accepted payment methods e.g. ['ONLINE', 'CARD', 'CASH']"),
        ),
        migrations.AddField(
            model_name='business',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0, help_text='Deposit amount in Toman'),
        ),
        migrations.AddField(
            model_name='business',
            name='deposit_mode',
            field=models.CharField(choices=[('NONE', 'بدون بیعانه'), ('MANDATORY', 'بیعانه اجباری'), ('OPTIONAL', 'بیعانه اختیاری')], default='NONE', help_text='Deposit requirement mode', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='max_appointments_per_hour',
            field=models.IntegerField(blank=True, help_text='Maximum concurrent appointments per hour. Null means unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='payment_method',
            field=models.CharField(choices=[('NONE', 'رایگان / بدون پیش\u200cپرداخت'), ('CARD', 'کارت به کارت'), ('GATEWAY', 'درگاه آنلاین (زیبال)')], default='NONE', help_text='How clients are charged when booking (Legacy)', max_length=10),
        ),
    ]
