# Generated by Django 4.2.29 on 2026-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_business_accepted_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='payment_link',
            field=models.URLField(blank=True, default='', help_text='Direct payment link (e.g. zarinpal.com/pay/...)'),
        ),
    ]
