# Generated by Django 4.2.29 on 2026-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_business_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
