# Generated by Django 5.2.16 on 2026-07-31 17:25

import business.models
from django.db import migrations, models


def backfill_cash_default(apps, schema_editor):
    """
    Every business created before this migration has accepted_payment_methods
    == [] — the old default — which left checkout with zero payment options to
    offer a client. Give those, and only those, CASH: a business that already
    has something configured (CARD, ONLINE, or CASH itself) is left untouched,
    so no owner's deliberate setup is overwritten.
    """
    Business = apps.get_model('business', 'Business')
    Business.objects.filter(accepted_payment_methods=[]).update(accepted_payment_methods=['CASH'])


def noop_reverse(apps, schema_editor):
    # Not reversible: we cannot tell a business that started at [] apart from
    # one an owner deliberately reset to CASH-only after this migration ran.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_business_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=business.models.Business._default_payment_methods, help_text="List of accepted payment methods e.g. ['ONLINE', 'CARD', 'CASH']"),
        ),
        migrations.RunPython(backfill_cash_default, noop_reverse),
    ]
