# Generated by Django 5.2.16 on 2026-07-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_cash_default_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='notify_owner_by_sms',
            field=models.BooleanField(default=True, help_text="Text the owner when a client books. Billed to the owner's own SMS quota, so it is switchable — an owner who watches the app does not have to pay for a message telling them what the app already shows."),
        ),
    ]
