# Generated by Django 6.0.7 on 2026-08-02 07:23

from django.db import migrations, models


def truncate_long_notices(apps, schema_editor):
    """Cut any existing notice down to the new 300-character cap.

    ``notice_message`` was an unbounded TextField, so on PostgreSQL the
    AlterField below runs ``ALTER COLUMN ... TYPE varchar(300)`` and aborts the
    whole migration with «value too long for type character varying(300)» if a
    single row is over. SQLite (dev) rebuilds the table and would silently keep
    the long value instead, leaving the two environments disagreeing. Doing the
    truncation here, before the column narrows, makes both behave the same.
    """
    Business = apps.get_model('business', 'Business')
    for pk, message in Business.objects.exclude(notice_message='').values_list('id', 'notice_message'):
        if message and len(message) > 300:
            Business.objects.filter(pk=pk).update(notice_message=message[:300])


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_business_notify_owner_by_sms'),
    ]

    operations = [
        migrations.RunPython(truncate_long_notices, migrations.RunPython.noop),
        migrations.AddField(
            model_name='business',
            name='notice_enabled',
            field=models.BooleanField(default=False, help_text='If True, notice_message is shown to clients on the booking page'),
        ),
        migrations.AddField(
            model_name='business',
            name='reminder_delivery',
            field=models.CharField(choices=[('MANUAL', 'ارسال دستی از سیم\u200cکارت اونر'), ('PANEL', 'ارسال خودکار از پنل پیامکی')], default='MANUAL', help_text="How appointment reminders reach clients: owner's SIM (free) or SMS panel (paid)", max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='notice_message',
            field=models.CharField(blank=True, default='', help_text='A short notice shown to clients on the booking page (max 300 chars)', max_length=300),
        ),
        migrations.AlterField(
            model_name='business',
            name='notify_owner_by_sms',
            field=models.BooleanField(default=False, help_text="Text the owner when a client books. Off by default: the owner is meant to learn about a booking from the app's own notification, not from an SMS billed to their own quota. Left switchable for owners who explicitly want to pay for it."),
        ),
    ]
