# Generated by Django 4.2.29 on 2026-08-08 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitor', '0006_alter_smslog_visitor'),
        ('business', '0011_business_notify_owner_by_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('LOW', 'کم — فقط نشانه\u200cگذاری'), ('HIGH', 'زیاد — بررسی فوری')], default='LOW', max_length=10)),
                ('note', models.CharField(blank=True, default='', help_text='چرا این کلمه اضافه شده', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'banned_keyword',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='BusinessModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_moderation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'محتوای نامناسب'), ('MISLEADING', 'اطلاعات گمراه\u200cکننده'), ('IMPERSONATION', 'جعل هویت'), ('ILLEGAL', 'فعالیت غیرقانونی'), ('SPAM', 'اسپم'), ('OTHER', 'سایر')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'جدید'), ('REVIEWING', 'در حال بررسی'), ('ACTIONED', 'اقدام شد'), ('DISMISSED', 'رد شد')], db_index=True, default='NEW', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='business',
            name='moderation_note',
            field=models.TextField(blank=True, default='', help_text="Reviewer's reason for rejection/suspension. Shown to the owner."),
        ),
        migrations.AddField(
            model_name='business',
            name='moderation_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='moderation_reviewed_by',
            field=models.ForeignKey(blank=True, help_text="Staff member who last decided this business's status.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده'), ('SUSPENDED', 'معلق شده')], db_index=True, default='PENDING', help_text='Editorial review state. Only APPROVED is publicly visible.', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='moderation_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When this business last entered the review queue. Drives queue ordering (oldest waiting first).', null=True),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['moderation_status', 'moderation_submitted_at'], name='biz_moderation_queue_idx'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='business.business'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='reporter_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to='visitor.visitor'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmoderationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmoderationlog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='business.business'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['status', '-created_at'], name='content_report_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmoderationlog',
            index=models.Index(fields=['business', '-created_at'], name='biz_mod_log_recent_idx'),
        ),
    ]
