# Generated by Django 4.2.29 on 2026-08-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_approve_existing_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreport',
            name='resulting_moderation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to='business.businessmoderationlog'),
        ),
    ]
