# Generated by Django 4.2.29 on 2026-08-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_stop_owner_booking_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BEAUTY_SALON', 'آرایشگاه و سالن زیبایی'), ('DOCTOR', 'پزشک و کلینیک'), ('CONSULTANT', 'مشاوره'), ('OTHER', 'سایر')], db_index=True, help_text='Shared across every business in this category', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_service_catalog_item',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'name'], name='business_se_categor_dfc8af_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicecatalogitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_service_catalog_category_name'),
        ),
    ]
