# Generated by Django 4.2.29 on 2026-08-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_contentreport_resulting_moderation_log'),
        ('business', '0015_business_services_and_more'),
    ]

    operations = [
    ]
