# Generated by Django 4.2.29 on 2026-08-29 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_restore_wrongly_hidden_businesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='unique_code',
            field=models.CharField(blank=True, db_index=True, help_text='کد یکتای عمومی کسب\u200cوکار؛ همان چیزی که در آدرس صفحهٔ رزرو می\u200cآید (\u200f/b/Noobatyar-<کد>). اگر خالی بماند یک کد ۸ کاراکتری خودکار ساخته می\u200cشود. برای کد دلخواه تا ۶۴ کاراکتر مجاز است. توجه: تغییر کد، لینک\u200cهای قبلیِ همین کسب\u200cوکار را از کار می\u200cاندازد.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='کد فقط می\u200cتواند شامل حروف انگلیسی، رقم، خط تیره (-) و زیرخط (_) باشد.', regex='^[A-Za-z0-9_-]+$')]),
        ),
    ]
