# Generated by Django 4.2.29 on 2026-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_business_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('DOCTOR', 'پزشک و کلینیک'), ('DENTIST', 'دندان\u200cپزشکی'), ('PSYCHOLOGY', 'روان\u200cشناسی و روان\u200cپزشکی'), ('PHYSIOTHERAPY', 'فیزیوتراپی و توان\u200cبخشی'), ('NUTRITION', 'تغذیه و رژیم\u200cدرمانی'), ('LABORATORY', 'آزمایشگاه و تصویربرداری'), ('OPTOMETRY', 'بینایی\u200cسنجی و عینک'), ('SPEECH_THERAPY', 'گفتاردرمانی'), ('MIDWIFERY', 'مامایی و سلامت بانوان'), ('VETERINARY', 'دامپزشکی'), ('BEAUTY_SALON', 'آرایشگاه و سالن زیبایی'), ('BARBERSHOP', 'آرایشگاه مردانه'), ('NAIL_SALON', 'سالن ناخن'), ('SKIN_LASER', 'پوست، مو و لیزر'), ('TATTOO', 'تتو و میکروپیگمنتیشن'), ('MASSAGE_SPA', 'ماساژ و اسپا'), ('CONSULTANT', 'مشاوره'), ('LAWYER', 'وکالت و مشاوره حقوقی'), ('ACCOUNTING', 'حسابداری و مالیات'), ('REAL_ESTATE', 'املاک و مستغلات'), ('INSURANCE', 'بیمه'), ('IMMIGRATION', 'مهاجرت و ویزا'), ('TUTORING', 'تدریس و کلاس خصوصی'), ('LANGUAGE_SCHOOL', 'آموزشگاه زبان'), ('MUSIC_SCHOOL', 'آموزش موسیقی'), ('GYM', 'باشگاه ورزشی و مربی شخصی'), ('YOGA_PILATES', 'یوگا و پیلاتس'), ('DRIVING_SCHOOL', 'آموزشگاه رانندگی'), ('AUTO_SERVICE', 'تعمیرگاه و خدمات خودرو'), ('CAR_WASH', 'کارواش و دیتیلینگ'), ('HOME_SERVICE', 'خدمات و تعمیرات منزل'), ('DEVICE_REPAIR', 'تعمیر موبایل و لوازم برقی'), ('TAILORING', 'خیاطی و طراحی لباس'), ('PHOTOGRAPHY', 'عکاسی و آتلیه'), ('EVENT_SERVICES', 'تالار و خدمات مراسم'), ('PET_GROOMING', 'آرایش و نگهداری حیوانات'), ('OTHER', 'سایر')], default='OTHER', help_text='Business category', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicecatalogitem',
            name='category',
            field=models.CharField(choices=[('DOCTOR', 'پزشک و کلینیک'), ('DENTIST', 'دندان\u200cپزشکی'), ('PSYCHOLOGY', 'روان\u200cشناسی و روان\u200cپزشکی'), ('PHYSIOTHERAPY', 'فیزیوتراپی و توان\u200cبخشی'), ('NUTRITION', 'تغذیه و رژیم\u200cدرمانی'), ('LABORATORY', 'آزمایشگاه و تصویربرداری'), ('OPTOMETRY', 'بینایی\u200cسنجی و عینک'), ('SPEECH_THERAPY', 'گفتاردرمانی'), ('MIDWIFERY', 'مامایی و سلامت بانوان'), ('VETERINARY', 'دامپزشکی'), ('BEAUTY_SALON', 'آرایشگاه و سالن زیبایی'), ('BARBERSHOP', 'آرایشگاه مردانه'), ('NAIL_SALON', 'سالن ناخن'), ('SKIN_LASER', 'پوست، مو و لیزر'), ('TATTOO', 'تتو و میکروپیگمنتیشن'), ('MASSAGE_SPA', 'ماساژ و اسپا'), ('CONSULTANT', 'مشاوره'), ('LAWYER', 'وکالت و مشاوره حقوقی'), ('ACCOUNTING', 'حسابداری و مالیات'), ('REAL_ESTATE', 'املاک و مستغلات'), ('INSURANCE', 'بیمه'), ('IMMIGRATION', 'مهاجرت و ویزا'), ('TUTORING', 'تدریس و کلاس خصوصی'), ('LANGUAGE_SCHOOL', 'آموزشگاه زبان'), ('MUSIC_SCHOOL', 'آموزش موسیقی'), ('GYM', 'باشگاه ورزشی و مربی شخصی'), ('YOGA_PILATES', 'یوگا و پیلاتس'), ('DRIVING_SCHOOL', 'آموزشگاه رانندگی'), ('AUTO_SERVICE', 'تعمیرگاه و خدمات خودرو'), ('CAR_WASH', 'کارواش و دیتیلینگ'), ('HOME_SERVICE', 'خدمات و تعمیرات منزل'), ('DEVICE_REPAIR', 'تعمیر موبایل و لوازم برقی'), ('TAILORING', 'خیاطی و طراحی لباس'), ('PHOTOGRAPHY', 'عکاسی و آتلیه'), ('EVENT_SERVICES', 'تالار و خدمات مراسم'), ('PET_GROOMING', 'آرایش و نگهداری حیوانات'), ('OTHER', 'سایر')], db_index=True, help_text='Shared across every business in this category', max_length=50),
        ),
    ]
