# Generated by Django 4.2.29 on 2026-08-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('kind', models.CharField(choices=[('visitor', 'مراجع'), ('owner', 'صاحب کسب\u200cوکار')], max_length=10, verbose_name='نوع مخاطب')),
                ('definition', models.JSONField(blank=True, default=dict, verbose_name='فیلترها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_segments', to=settings.AUTH_USER_MODEL, verbose_name='ساخته\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'گروه مخاطب',
                'verbose_name_plural': 'گروه\u200cهای مخاطب',
                'db_table': 'core_audience_segment',
                'ordering': ['-created_at'],
                'permissions': [('export_pii', 'می\u200cتواند خروجی شماره\u200cتلفن/فهرست مخاطب بگیرد')],
            },
        ),
        migrations.CreateModel(
            name='AudienceSegmentExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('visitor', 'مراجع'), ('owner', 'صاحب کسب\u200cوکار')], max_length=10, verbose_name='نوع مخاطب')),
                ('definition', models.JSONField(blank=True, default=dict, verbose_name='فیلترهای اجراشده')),
                ('row_count', models.PositiveIntegerField(verbose_name='تعداد ردیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان خروجی')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_segment_exports', to=settings.AUTH_USER_MODEL, verbose_name='گرفته\u200cشده توسط')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='core.audiencesegment', verbose_name='گروه مخاطب')),
            ],
            options={
                'verbose_name': 'خروجی گروه مخاطب',
                'verbose_name_plural': 'خروجی\u200cهای گروه مخاطب',
                'db_table': 'core_audience_segment_export',
                'ordering': ['-created_at'],
            },
        ),
    ]
