# Generated by Django 4.2.29 on 2026-08-29 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_restore_wrongly_hidden_businesses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('PUSH', 'اعلان'), ('SMS', 'پیامک')], max_length=10, verbose_name='کانال')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('SENT', 'ارسال\u200cشده'), ('FAILED', 'ناموفق')], max_length=10, verbose_name='وضعیت')),
                ('error_detail', models.TextField(blank=True, verbose_name='جزئیات خطا')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_message_logs', to='business.business', verbose_name='کسب\u200cوکار')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'پیام ادمین به کسب\u200cوکار',
                'verbose_name_plural': 'پیام\u200cهای ادمین به کسب\u200cوکارها',
                'db_table': 'core_admin_message_log',
                'ordering': ['-sent_at'],
                'permissions': [('send_business_message', 'می\u200cتواند به کسب\u200cوکارها پیام/اعلان بفرستد')],
            },
        ),
    ]
