# Generated by Django 4.2.29 on 2026-08-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_adminmessagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.JSONField(blank=True, default=dict, verbose_name='فیلترهای اجراشده')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('recipient_count', models.PositiveIntegerField(verbose_name='تعداد مخاطب واجد شرایط')),
                ('delivered_count', models.PositiveIntegerField(verbose_name='تعداد تحویل\u200cشده')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_marketing_pushes', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'کمپین پوش تبلیغاتی',
                'verbose_name_plural': 'کمپین\u200cهای پوش تبلیغاتی',
                'db_table': 'core_marketing_push_log',
                'ordering': ['-sent_at'],
                'permissions': [('send_marketing_push', 'می\u200cتواند پوش تبلیغاتی برای گروه مخاطب ارسال کند')],
            },
        ),
    ]
