# Generated by Django 4.2.29 on 2026-09-02 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marketingpushlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpushlog',
            name='audience',
            field=models.CharField(choices=[('visitor', 'مشتریان'), ('owner', 'صاحبان کسب\u200cوکار')], default='visitor', max_length=10, verbose_name='مخاطب'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='dead_token_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد توکن منقضی'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='deep_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='دیپ\u200cلینک'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ناموفق'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='شناسه کمپین'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='marketingpushlog',
            name='reachable_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دارای اعلان فعال'),
        ),
        migrations.AlterField(
            model_name='marketingpushlog',
            name='delivered_count',
            field=models.PositiveIntegerField(verbose_name='تعداد پذیرفته\u200cشده توسط فایربیس'),
        ),
    ]
